### ISSUE TITLE
Use GeoPy to derive locations's elevation

### ISSUE THREAD

**Issue by dspreitz** [tobiz/OGN-Flight-Logger#11]
Presently the altitude information of the airfield must be given in the settings.py file.
Using GeoPy this information can be derived based on lat/lon.
http://geopy.readthedocs.org/en/latest/

Google Maps also offers a corresponding API:
https://developers.google.com/maps/documentation/elevation/

**Comment by tobiz** [comment]
Dominic,

Thanks for this; I'll take a look

Peter J Robinson

**Comment by tobiz** [comment]
Included in V0.2.2.
Note this can not be used in an offline version
