### ISSUE TITLE
OGN_db.py creates duplicate entries in flogger.sql3

### ISSUE THREAD

**Issue by dspreitz** [tobiz/OGN-Flight-Logger#4]
OGN_db.py creates duplicate entries in flogger.sql3 each time it is re-run. Some db cleanup must be added at the end of code

**Comment by tobiz** [comment]
Ok understood.  This has been fixed in the latest master version I have.  I'm also considering how to include your other enhancements and when complete will upload this version.

**Comment by tobiz** [comment]
This has now been fixed along with many other changes and improvements.
